// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyv54OZpLPQvj9yQjQdDYImabuVtX5cC0',
    appId: '1:144165828319:android:a4942292c99e8d1e0ddb6a',
    messagingSenderId: '144165828319',
    projectId: 'firebox-349ab',
    storageBucket: 'firebox-349ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmbBIpKmqZFYCB42rNjW6rfipW7_5FvYA',
    appId: '1:144165828319:ios:8498d95fdb7c63a70ddb6a',
    messagingSenderId: '144165828319',
    projectId: 'firebox-349ab',
    storageBucket: 'firebox-349ab.appspot.com',
    androidClientId: '144165828319-08gd88v4s9cvueuo9pdh30kuk2fn91j8.apps.googleusercontent.com',
    iosClientId: '144165828319-cdi2m3u6gbdmes2gab42rlrqnnn2c9ki.apps.googleusercontent.com',
    iosBundleId: 'com.example.firesportUsers',
  );

}